version: "3.5"

services:


  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: deniz
      POSTGRES_DB: hibernate
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always


volumes:
  data-postgres:
    name: data-postgres

